packages:
  - packages/*
  - samples/**

# minimumReleaseAge: 1440
# minimumReleaseAgeExclude:
#   - '@workleap*'
#   - '@typescript/native-preview*'

onlyBuiltDependencies:
  - agent-browser
  - '@parcel/watcher'
  - '@swc/core'
  - core-js
  - core-js-pure
  - esbuild
  - msw
  - netlify-cli
  - protobufjs
  - sharp
  - unix-dgram

patchedDependencies:
  logrocket@12.0.0: patches/logrocket@12.0.0.patch
