packages:
  - packages/*
  - samples/**

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - agent-browser
  - core-js
  - core-js-pure
  - edgedriver
  - esbuild
  - geckodriver
  - msw
  - netlify-cli
  - protobufjs
  - sharp
  - unix-dgram

patchedDependencies:
  logrocket@12.0.0: patches/logrocket@12.0.0.patch
